### PR TITLE
Implemented create stake

### PR DESCRIPTION
**Pull request by acaldas**

### CODE REVIEW

**Review by NathanTarbert — APPROVED** [review]

**Comment by passandscore** [comment]
Have you confirmed functionality with this commit? Can you create stake and fetch stakes with no problems at this point?

**Comment by acaldas** [comment]
I can create and fetch the stakes but I have not deployed the new staking contract with the duration fix

**Review by passandscore — APPROVED** [review]
I like this. Much nicer to read. We will have to redeploy the contract or create a V2 for it to be onchain. We don't need to change the contract on chain at this time as the deployed version produces the same result. Merge changes when we add a new feature or a logic change to this contract, we will upgrade onchain.

**Comment by acaldas** [comment]
@passandscore We need to redeploy with these fixes to calculate the duration and reward.
The duration timestamps had an extra zero for 1 day and 2 weeks. If you check the seconds for one day were bigger than for a week (864000 vs 604800)

The reward was returning with 36 decimals, maybe ether is the wrong unit for the reward rate?
I tested it locally on remix and got the right value with this code change.

**Pull request merged**
