### PR TITLE
Added Contributing.md to root

### PR DESCRIPTION
**Pull request by ankits57**

### CODE REVIEW

**Comment by NathanTarbert** [comment]
Hi @ankits57, can you change the link of the CODE_OF_CONDUCT and link it to the .github file?

**Comment by ankits57** [comment]
Yeah sure

**Comment by NathanTarbert** [comment]
Ok, thanks. Let me know when it's done.

**Review by NathanTarbert — APPROVED** [review]

**Review by NathanTarbert — APPROVED** [review]

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Thanks @ankits57 for your contribution!

**Pull request merged**
