### PR TITLE
Add docker file1

### PR DESCRIPTION
**Pull request by NathanTarbert**
**Make sure Docker is running and you are logged in...**

**To build the container:**

docker build -t `my-app-name` .

**To run the app via container:**

docker run -p 3000:3000 `my-app-name`

### CODE REVIEW

**Comment by passandscore** [comment]
Are we still wanting everyone to run our application via Docker now that we have a basic way of handling env variables?

If so, I guess that is fine as it ensures that the dapp runs for all users regardless of architecture.

You should update the readme installation instructions in this MR.

**Comment by NathanTarbert** [comment]
I like the fact that it bundles all of the dependencies no matter what the deployment method is so I think it's good to have.

**Comment by NathanTarbert** [comment]
Added the Docker build script to the package.json and updated the README to add the build steps.

**Comment by NathanTarbert** [comment]
Now it's not necessary to run the Docker compose build, just run `yarn docker` and go to `localhost:3000`

**Comment by passandscore** [comment]
error when following the readMe

Screenshot 2023-10-24 at 8 28 53 PM

**Review by passandscore — APPROVED** [review]

**Pull request merged**
